version: "3.8"
services:
  app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./app
    links:
        - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"